### ISSUE TITLE
【issues】when I include libwebrtc-m122.aar ,I met “Unsupported class file major version 61“

### ISSUE THREAD

**Issue by dualven** [AhmedHumk/Webrtc-AAr-Build-Releases#1]
https://blog.csdn.net/dualvencsdn/article/details/138145528

**Comment by dualven** [comment]
@AhmedHumk

**Comment by AhmedHumk** [comment]
your issue relays on the java version that you are using for development environment. which you didnt mentioned which version of java jdk that you are using !

**Comment by dualven** [comment]
if I use jdk11 ,  can't I use *.aar which compiled by jdk17?

**Comment by AhmedHumk** [comment]
it doesn't matter which version of java the AAR compiled with ! as a big example I have compiled m123 latest version with **JDK 11**! you will get the same message Unsupported class file major version 61! 
if you want to use most recent webrtc aar with java 11 use **M119**. its compatible with jdk11 java source!

**Comment by dualven** [comment]
I also compile the project myself.  I wonder what matters the compatition .  
what configuration should I  set in the project   when I want to make the aar compatible with jdk11?
2024-04-26 

dualven 



发件人：Ahmed Hussein ***@***.***>
发送时间：2024-04-25 23:24
主题：Re: [AhmedHumk/Webrtc-AAr-Build-Releases] 【issues】when I include libwebrtc-m122.aar ,I met “Unsupported class file major version 61“ (Issue #1)
***@***.***>
***@***.***>***@***.***>

it doesn't matter which version of java the AAR compiled with ! as a big example I have compiled m123 latest version with JDK 11! you will get the same message Unsupported class file major version 61!
if you want to use most recent webrtc aar with java 11 use M119. its compatible with jdk11 java source!
